RedHatInsights/insights-remediations-frontend

.babelrc
package-lock.json
package.json
src/components/CreatePlanModal/ModalSteps/PlanName.js

Fixes typing inside of Create Modal naming input

---

src/api.js
src/components/ConfirmationDialog.js
src/components/DeleteButton.js
src/containers/ConnectedComponents.js
src/routes/RemediationDetails.js

show confirmation modal when removing remediation

---

src/actions.js
src/api.js
src/components/RemediationDetailsTable.js
src/constants.js
src/containers/ConnectedComponents.js
src/routes/RemediationDetails.js
src/store/reducers.js

depends on https://github.com/RedHatInsights/insights-remediations-frontend/pull/22

 implement removing actions in RemediationDetailsTable

---

package-lock.json
src/routes/RemediationDetails.js
src/routes/RemediationDetails.scss
src/skeletons/RemediationDetailsSkeleton.js
src/skeletons/RemediationDetailsSkeleton.scss

Related: #39 
On hold until #38 merges

adding skeleton for details page

---

src/components/RemediationTable.js
src/routes/RemediationDetails.js
src/skeletons/RemediationDetailsSkeleton.js

Renaming remediation to playbook in some cases

---

package-lock.json
package.json
src/components/RemediationDetailsTable.js
src/components/RemediationTable.js
src/components/RemediationTable.scss
src/skeletons/RemediationDetailsSkeleton.js

On hold until https://github.com/RedHatInsights/insights-frontend-components/pull/275

adding table toolbar

---

package-lock.json
package.json
src/components/RemediationDetailsTable.js
src/components/RemediationTable.js

On hold until: https://github.com/RedHatInsights/insights-frontend-components/pull/289

updating tables to show result count

---

src/Utilities/model.js

Will update the urls whenever Inventory changes

updating advisor type to insights

---

src/App.scss
src/routes/RemediationDetails.js

Currently, PF has this variant on their roadmap.
Until then, this styling should do and correctly reflects what it will look like.

Updating page-header buttons

---

src/components/RemediationDetailsTable.js
src/routes/RemediationDetails.js

Disabling buttons if empty playbook

---

src/components/TestButtons.js

See https://docs.google.com/spreadsheets/d/1nje3ysBzsW_oRC0jXiaeS5QWjySFIOZ1uay7FlKUXfw/edit#gid=2142672983 for details

improve Remediation wizard test buttons

---

src/components/RemediationDetailsTable.js

use TableVariant.compact for remediation details table

---

package-lock.json
package.json

mostly to get https://github.com/RedHatInsights/insights-frontend-components/commit/d36a30e74b9c4033d87f97748ef23be71f63e009

upgrade ifc to 3.34.5

---

src/components/RemediationDetailsTable.js

On hold until: https://github.com/RedHatInsights/insights-frontend-components/pull/303

adding empty table for results when empty

---

config/base.webpack.plugins.js
config/dev.webpack.config.js
config/spandx.config.local.js
config/webpack.common.js
src/Routes.js
src/entry-dev.js
src/entry.js
src/index.html

Getting a 500 from the API and not getting the right navigation

First draft of c.rh.c

---

package-lock.json
package.json
src/actions.js
src/api.js
src/components/ResolutionEditButton.js
src/components/ResolutionModal/ResolutionStep.js
src/constants.js
src/containers/ConnectedComponents.js
src/routes/Home.js
src/routes/RemediationDetails.js

https://projects.engineering.redhat.com/browse/RHIPLAT2-445

use generated API client

---

package-lock.json
package.json
src/components/RemediationDetailsTable.js
src/components/RemediationTable.js
src/routes/RemediationDetails.js
src/skeletons/RemediationDetailsSkeleton.js
src/skeletons/SkeletonTable.js
src/skeletons/SkeletonTable.scss

Main Page:
- update skeleton to right align table footer
- change dates to be relative to today
Details
- Move "created" in playbook details to the body of the card
- Make dates relative to today
- If reboot is required in table, use check instead of "yes"
- update skeleton to right align table footer
Table Skeleton
- Use spinner in table body

Updating to reflect new mocks

---

config/spandx.config.js
config/webpack.common.js
src/Utilities/urls.js

Updated:
* playbook URL
* system URL should use inventory on current path (insights or rhcs)
* add conditional checking for beta on both

Updating URLs on details page

---

src/Utilities/urls.js
src/components/RemediationTable.js

https://projects.engineering.redhat.com/browse/RHIPLAT2-685

more cross-app URL fixes

---

src/actions.js
src/components/RemediationDetailsTable.js
src/components/RemediationTable.js
src/components/TestButtons.js
src/containers/DeleteButtons.js
src/containers/ToolbarActions.js
src/hooks/table.js
src/routes/Home.js

https://projects.engineering.redhat.com/browse/RHIPLAT2-545

switch to server-side pagination

---

package-lock.json
package.json
src/Routes.js
src/routes/FindItFixIt.js
src/routes/FindItFixIt.scss
src/routes/launch.fsm.js
src/routes/logic.js

This PR still needs restricting the UI to beta users and possibly to certain user ids.

Adds FindItFixIt to Remediations app

---

package-lock.json
package.json
src/App.scss
src/components/ConfirmationDialog.js
src/components/Dialogs/TextInputDialog.js
src/components/RemediationDetailsDropdown.js
src/containers/DeleteButtons.js
src/routes/RemediationDetails.js
src/skeletons/RemediationDetailsSkeleton.js
src/store/reducers.js

https://projects.engineering.redhat.com/browse/RHCLOUD-1024

as a user I can rename a remediation

---

src/Utilities/model.js

https://projects.engineering.redhat.com/browse/RHCLOUD-1260

use UTC for absolute time

---

.travis.yml

Add codecov after verify is successfull

---

src/components/RemediationDetailsTable.js
src/components/RemediationDetailsTable.scss

changed Icon and added 'No' response to replace empty

---

src/components/ExecuteButton.js

Fix loading state of Execute Playbook modal

Fix loading state of Execute Playbook modal

---

src/Utilities/model.js
src/Utilities/urls.js
src/components/TestButtons.js

https://projects.engineering.redhat.com/browse/RHCLOUD-4230

RHCLOUD-4230 Patch Manager support in frontend

---

package-lock.json
src/actions.js
src/components/ExecuteButton.js
src/constants.js
src/containers/ExecuteButtons.js
src/routes/RemediationDetails.js
src/store/reducers.js

Jira: [Here](https://projects.engineering.redhat.com/browse/RHCLOUD-3715)

Execute alert banner

---

src/components/RemediationDetailsTable.js
src/components/SystemForActionButton.js
src/store/reducers.js

Add new modal that displays system for remediation.
We don't have data to for `Connection type` column, so we can't filter a group by type yet.
https://projects.engineering.redhat.com/browse/RHCLOUD-3622

Systems for action modal

---

src/components/SystemForActionButton.js
src/store/reducers.js

Add sorting and links to Systems for action table.

Add sorting and links to Systems for action table

---

src/components/Layouts/DescriptionList.js
src/components/Layouts/DescriptionList.scss
src/components/Layouts/__tests__/DescriptionList.test.js
src/components/Layouts/__tests__/__snapshots__/DescriptionList.test.js.snap
src/routes/RemediationDetails.js
src/routes/RemediationDetails.scss
src/skeletons/RemediationDetailsSkeleton.js
src/skeletons/RemediationDetailsSkeleton.scss

Plan summary card

---

src/components/Alerts/UpsellBanner.js
src/components/Alerts/__tests__/UpsellBanner.test.js
src/components/Alerts/__tests__/__snapshots__/UpsellBanner.test.js.snap
src/components/ExecuteButton.js
src/routes/RemediationDetails.js

Mocks: https://marvelapp.com/j3b9b7e/screen/63670944
Jira: https://projects.engineering.redhat.com/browse/RHCLOUD-4244

add upsell banner and logic for unentitled users

---

src/App.js
src/components/DeniedState.js
src/components/ExecuteButton.js
src/components/RemediationDetailsDropdown.js
src/components/RemediationDetailsTable.js
src/components/RemediationTable.js
src/routes/Home.js
src/routes/RemediationDetails.js
src/skeletons/GlobalSkeleton.js
src/skeletons/RemediationDetailsSkeleton.js

implement RBAC roles in the UI
https://projects.engineering.redhat.com/browse/RHCLOUD-4500

Implement RBAC in the UI

---

package-lock.json
package.json
src/App.js
src/components/ExecuteButton.js
src/components/ExecuteButton.test.js
src/components/__snapshots__/ExecuteButton.test.js.snap
src/containers/ExecuteButtons.js
src/routes/RemediationDetails.js

This also moves the smart management check to `App.js` and passes it with the context. Since this does touch the other states, you can simulate permissions, check whether receptor is configured, and smart management entitlement by editing the context in `App.js`

Rewrite RemediationDetails to use hooks, update page when execution, add timer to update info

---

src/components/ExecutorDetails.js
src/routes/RemediationDetails.js

Stop refresh after completing run

---

src/components/ExecutorDetails.js

Fix reloading Inventory table on expand

Fix relaoding on Expand

---

src/components/ExecutorDetails.js

Fix Executor detail system pagination
https://projects.engineering.redhat.com/browse/RHCLOUD-5961

Fix Executor detail system pagination

---

src/components/Alerts/NoReceptorBanner.js
src/components/Alerts/UpsellBanner.js
src/components/Alerts/__tests__/__snapshots__/UpsellBanner.test.js.snap
src/components/EmptyStates/ActivityTabUpsell.js
src/components/ExecuteButton.js
src/routes/RemediationDetails.js

As per:
https://docs.google.com/document/d/1UahNttvwk7A1HACQMZ9DE-ufN3ODXqZpbgE4WTaDrxU/edit?usp=sharing

add links and hide other links

---

package-lock.json
package.json
src/actions.js
src/components/ExecutorDetails.js
src/store/reducers.js

Add server side filtering
https://projects.engineering.redhat.com/browse/RHCLOUD-5989
https://projects.engineering.redhat.com/browse/RHCLOUD-5992
EDIT:  API issues has been fixed

Add server side filtering

---

src/Utilities/debug.js

Fix js error at Remediation detail page
https://projects.engineering.redhat.com/browse/RHCLOUD-5313

Fix pagination types

---

src/components/ExecutorDetails.js
src/components/SystemForActionButton.js

Fix js errors at both Inventory tables in Remediations.
https://projects.engineering.redhat.com/browse/RHCLOUD-5313

Fix Inventory props

---

src/components/statusHelper.js

Fix spelling of succeeded.
https://projects.engineering.redhat.com/browse/RHCLOUD-6702

Fix spelling of succeeded in execution status

---

package-lock.json
src/components/ExecutorDetails.js
src/components/Status.scss
src/components/statusHelper.js

Added normalized canceled status to improve transparity in the event that a playbook run is canceled.  
JIRA:  https://projects.engineering.redhat.com/browse/RHCLOUD-6574

RHCLOUD-6574: add normalized cancel status

---

package-lock.json
src/Utilities/model.js
src/Utilities/urls.js

Also correcting the url formation for advisor actions.

Correcting remediation type when action is from advisor.

---

src/Utilities/model.js
src/Utilities/urls.js
src/components/statusHelper.js

Jira links:
- https://projects.engineering.redhat.com/browse/RHCLOUD-6416
- https://projects.engineering.redhat.com/browse/RHCLOUD-6372
- https://projects.engineering.redhat.com/browse/RHCLOUD-7080

Bug fixes for RHCLOUD-6416/6372/7080

---

src/components/RemediationTable.js

Jiras: 
- https://projects.engineering.redhat.com/browse/RHCLOUD-7666
- https://projects.engineering.redhat.com/browse/RHCLOUD-7667
- https://projects.engineering.redhat.com/browse/RHCLOUD-7669

Bug fixes for an empty remediations list and delete functionality in beta

---

package-lock.json
package.json
src/actions.js
src/api.js
src/components/ExecuteButton.js
src/components/Modals/ExecuteModal.js
src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap
src/components/__tests__/ExecuteButton.test.js
src/components/__tests__/__snapshots__/ExecuteButton.test.js.snap
src/components/statusHelper.js
src/config.js
src/constants.js
src/containers/ExecuteButtons.js
src/store/reducers.js

Hook Execute playbook modal to Sources api.
DO NOT merge this before summit.
https://projects.engineering.redhat.com/browse/RHCLOUD-5817

Hook Execute modal to Sources

---

src/components/ConfirmationDialog.js
src/routes/Home.js

Updating remediations delete dialogue to show correct title and text

---

package-lock.json
package.json
src/Utilities/urls.js
src/api.js
src/routes/Home.js

- Added ability to download multiple playbooks as a zip file (https://issues.redhat.com/browse/RHCLOUD-9751)
- Updated url generation for links to 'patch' issues (https://issues.redhat.com/browse/RHCLOUD-9150)
- Added notifications for downloads (https://issues.redhat.com/browse/RHCLOUD-5897)

Downloading multiple playbooks in a zip file

---

package-lock.json
package.json

cc @karelhala @aleccohan 
applies changes in: https://github.com/RedHatInsights/frontend-components/pull/771

Update remediations wizard.

---

src/index.html
src/routes/Home.js
src/routes/RemediationDetails.js

https://issues.redhat.com/browse/RHCLOUD-8794

Fix tab titles

---

src/skeletons/RemediationDetailsSkeleton.js
src/skeletons/SkeletonTableToolbar.js
src/skeletons/SkeletonTabs.js

https://issues.redhat.com/browse/RHCLOUD-8916

redo skeleton for details page

---

src/routes/Home.scss

Jira: https://issues.redhat.com/browse/RHCLOUD-13022
- Right align dropdowns in mobile to prevent cropping
- Make buttons emulate link styling when in kebab 
Old
New
Old
New

Toolbar dropdown mobile fixes

---

src/actions.js
src/api.js
src/components/SystemsTable/IssuesColumn.js
src/components/SystemsTable/RebootColumn.js
src/components/SystemsTable/RemoveSystemModal.js
src/components/SystemsTable/SystemsTable.js
src/components/SystemsTable/SystemsTable.scss
src/components/SystemsTable/helpers.js
src/components/SystemsTable/helpers.test.js
src/components/SystemsTable/index.js
src/components/statusHelper.js
src/constants.js
src/routes/RemediationDetails.js
src/skeletons/SkeletonTabs.js
src/store/reducers.js

JIRA: https://issues.redhat.com/browse/RHCLOUD-13786

Add systems tab to remediations detail

---

src/components/Alerts/NoReceptorBanner.js

https://bugzilla.redhat.com/show_bug.cgi?id=1941862

Updating url for no receptor configured

---

src/components/Alerts/NoReceptorBanner.js

* Updating url for no receptor configured (#226)

Push to stable envs

---

src/components/Modals/ExecuteModal.js
src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap

- Use button span component to allow wrapping (prevent mobile layout from breaking)
- Add external link icons
- Force new window for links
Jira: https://issues.redhat.com/browse/RHCLOUD-14375
Old
New
cc @katierik

'Execute playbook" modal styling and mobile fixes

---

src/components/statusHelper.js

Add Cloud Connector docs urls

---

src/components/statusHelper.js

Aims to close [this card](https://issues.redhat.com/browse/RHCLOUD-14909)

Console link fix

---

package-lock.json
src/components/EmptyExecutePlaybookState.js
src/components/Modals/ExecuteModal.js
src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap

This PR aims to close [this card](https://issues.redhat.com/browse/RHCLOUD-14910)
_**Green square around x button is from trying to take screenshot**_
Also, any feedback to make the conditional rendering of the table portion is welcomed with open arms. Couldn't figure out a way to make it simpler/cleaner, and did not want to spin wheels on it :D

Adding empty state to execute modal without systems

---

src/routes/RemediationDetails.js

https://issues.redhat.com/browse/RHCLOUD-14323

disable execute playbook buton for fedramp

---

src/components/Modals/ExecuteModal.js

Jira: https://issues.redhat.com/browse/RHCLOUD-16117
Old
New

Fix playbook execution notification showing html styling

---

src/components/Alerts/RunFailed.js
src/components/CreatePlanModal/ModalSteps/PlanSystems.js
src/components/CreatePlanModal/ModalSteps/PlanSystems.scss
src/components/Layouts/DescriptionList.js
src/components/Layouts/DescriptionList.scss
src/components/Layouts/__tests__/__snapshots__/DescriptionList.test.js.snap
src/components/RemediationSummary.js
src/components/ResolutionEditButton.js
src/components/ResolutionModal/ChooseResolutionModal.scss
src/components/ResolutionStatusIcon.js
src/components/ResolutionStatusIcon.scss
src/components/Status.scss
src/components/SystemDetails.js
src/components/SystemDetails.scss
src/components/statusHelper.js
src/routes/RemediationDetails.js
src/skeletons/RemediationDetailsSkeleton.js

Jira: https://issues.redhat.com/browse/RHCLOUD-16723
Add "adv" prefix to classes
Use PF/Platform class naming convention

rescope class names

---

config/dev.webpack.config.js
package-lock.json
package.json
src/config.js

This updates the config package and sets the default chrome to `stage-stable`, since CI/QA are now decommissioned.

chore(devtools): RHIF-11 - Update webpack dev server config

---

src/components/Alerts/NoReceptorBanner.js

Updated link for cloud connecter doc per https://issues.redhat.com/browse/ESSNTL-785

Updated link for cloud connector documentation

---

src/components/EmptyStates/EmptyRemediations.js

UXD requirements document: https://docs.google.com/document/d/1rg_imN7ZrKDXG-cb6v3UOEzOsvKwdGzPcWpvO5_ijqg/edit#bookmark=id.8bb6llp51yyx

Update empty state text for 0 playbooks

---

package-lock.json
package.json

ESSNTL-2167
Updating the Log Viewer package fixes clipping issues

fix: Updated Log Viewer

---

src/components/PlaybookCard.js
src/components/PlaybookCard.scss

ESSNTL-786
Archived Remediations now look as requested:

fix: Updated Playbook Card design when archived

---

src/Utilities/utils.js
src/components/RemediationDetailsTable.js
src/components/SystemsTable/RebootColumn.js
src/modules/RemediationsModal/steps/issueResolution.js

Changed from Icon with Yes/No to Required/Not required

Changed Reboot required status text

---

src/components/Alerts/NoReceptorBanner.js
src/components/EmptyStates/NotConfigured.js
src/components/Modals/ExecuteModal.js
src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap
src/components/statusHelper.js

- change version to 2022
- update doc title in one instance

update docs urls

---

deploy/frontend.yaml

I messed up the name of the frontend deploy yaml file

File name change to match app-interface

---

package.json

Fixing the empty reports for remediations code coverage

feat(codecov):fixing code coverage

---

.github/pull_request_template.md
package-lock.json

introduces pull request template

chore: introduces pull request templates

---

src/components/RemediationDetailsTable.js

https://issues.redhat.com/browse/REMEDY-283
https://issues.redhat.com/browse/REMEDY-145
Fixing bulk select for remediation details
Need to write cypress tests when we have the library in place
Run it locally and test if it selects all the rows correctly

fix(ActionsTable): Fixing bulk select

---

src/components/Alerts/NoReceptorBanner.js
src/components/EmptyStates/NotConfigured.js
src/components/Modals/ExecuteModal.js
src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap
src/components/statusHelper.js

Where links to Insights, Console, Cost & Subscriptions docs exist, this PR updates the url to the 2023 version

update docs versions for Insights, Console, Cost & Subscriptions

---

.gitignore
config/setupTests.js
src/App.js
src/Utilities/http.js
src/api/index.js
src/components/Modals/ExecuteModal.js
src/components/TestButtons.js
src/components/statusHelper.js
src/modules/RemediationsButton.js
src/modules/tests/remediationButton.test.js

[RHIF-126] adopt useChrome hook

---

src/components/RemediationDetailsTable.js
src/config.js
src/containers/DeleteButtons.js
src/routes/RemediationDetails.js

Fixes https://issues.redhat.com/browse/RHIF-126.

refactor(RHIF-126): Fix chrome call in config.js

---

README.md
config/dev.webpack.config.js
config/spandx.config.js
package-lock.json
package.json
src/Utilities/urls.js
src/Utilities/utils.js
src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap
src/components/statusHelper.js

chore(rhif-223): Update /beta with /preview

---

.gitignore
src/App.js
src/components/Modals/ExecuteModal.js
src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap
src/components/PlaybookCard.js
src/components/statusHelper.js

Associated Jira ticket: # (RHIF-245)
This removes the smart management check on remediations as asked in the ticket.

fix(RHIF-245): remove smart management check

---

package.json
src/App.js

Tests containerization

---

src/routes/RemediationDetails.js

https://issues.redhat.com/browse/RHINENG-750

Update remediation button RBAC tooltip

---

src/Routes.js

App name was missing the 's' on the import.

fix(RHIF-199): Remediation zero state import fix

---

src/routes/RemediationDetails.js

fix(RemediationDetails): RHINENG-1534 - Make isOrgAdmin always a function

---

config/dev.webpack.config.js
config/prod.webpack.config.js

Adds the deployment tag/check to load proper assets in prod and stage envs.

fix(wepback): update webpack configs to contain deployment tag

---

src/components/Modals/SystemsStatusModal.js

Associated Jira ticket: [RHINENG-7884](https://issues.redhat.com/browse/RHINENG-7884)
Regression from `frontend-components` upgrade, `ConditionalFilter` has changed a bit

fix(RHINENG-7884): Remediation display systems list

---

src/components/Dialogs/TextInputDialog.js

Associated Jira ticket: # [(issue)](https://issues.redhat.com/browse/RHINENG-8341)
Removes unnecessary form helper text 

fix(RHINENG-8341): remove helper text asking for middlename

---

src/components/Alerts/NoReceptorBanner.js
src/components/EmptyStates/NotConfigured.js
src/components/Modals/ExecuteModal.js
src/components/statusHelper.js

Updates the doc links with new 1-latest subpath

chore(RHINENG-7106): update doc links with 1-latest

---

src/components/Dialogs/TextInputDialog.js
src/modules/RemediationsModal/schema.js
src/modules/RemediationsModal/steps/selectPlaybook.js

Associated Jira ticket: # ([issue](https://issues.redhat.com/browse/RHINENG-9905))
This just changes the error text for the remediation modals. If the playbook matches and existing one in either modal, the new message should appear.

fix(RHINENG-9905): Update modal error strings

---

package-lock.json
package.json

fix(deps): RHINENG-8448 - update frontend-components

---

src/Utilities/useConnectionStatus.js
src/components/SystemsTable/Columns.js
src/components/SystemsTable/ConnectionStatusCol.js
src/components/SystemsTable/SystemsTable.js
src/components/SystemsTable/helpers.js
src/components/SystemsTable/helpers.test.js
src/routes/RemediationDetails.js

Associated Jira ticket: # ([issue](https://issues.redhat.com/browse/RHINENG-9382))
This adds a connection status column to systems table in rem details 
Open up a remediations details and navigate to systems tab
Mocks: 
https://www.figma.com/proto/4SzBpdiqHzLDtItBG3aisz/Remediations?page-id=0%3A1&type=design&node-id=247-8196&viewport=358%2C-1266%2C0.16&t=qCljog3Q1nHLY3d1-1&scaling=min-zoom&starting-point-node-id=133%3A8687

feat(RHINENG-9382): Add connection status column

---

src/components/SystemsTable/ConnectionStatusCol.js

Updates the link for the unknown status popover

update link in connection_column

---

package-lock.json
package.json

https://issues.redhat.com/browse/RHINENG-8928

chore(deps): Update follow redirects to fix a CVE

---

README.md

fix(docs): Update npm run start command with proxy

---

README.md

docs(readme): add info about required /etc/hosts edit

---

package-lock.json
package.json

chore(RHINENG-10336): update cypress code-cov package

---

.tekton/remediations-frontend-pull-request.yaml
.tekton/remediations-frontend-push.yaml

feat(konflux): add new mandatory RPM signature scan task to tekton

---

.github/workflows/sentry.yml
.gitignore
fec.config.js
package-lock.json
package.json

This onboards Remediations to sentry to receive proper error reporting/routing, as well as the automation workflow that sends debugIDs up on a merge to master + sourceMap automation when a release is made too prod
https://issues.redhat.com/browse/RHINENG-15380

feat(RHINENG-15380): Onboard Remediations to Sentry Instance

---

renovate.json

feat(Konflux): Enable automerge

---

.github/CODEOWNERS

chore(Konflux): Remove condeowners for Konflux automerge

---

.gitmodules
.tekton/remediations-frontend-pull-request.yaml
.tekton/remediations-frontend-push.yaml

Associated Jira ticket: [RHINENG-16162](https://issues.redhat.com/browse/RHINENG-16162)
Use shared Dockerfile

chore(build): use shared Dockerfile

---

fec.config.js

Sentry isnt grabbing the authtoken in the docker step, experimenting with this path

fix(sentry): Add helper to grab authToken on build time
