RedHatInsights/insights-remediations-frontend

src/actions.js, src/api.js, src/components/CreatePlanModal/ModalSteps/PlanName.js, src/components/NewRemediationButton.js, src/constants.js, src/routes/Home.js
Not useful per se but serves temporarily as an easy way to create a new demo remediation and to verify that the frontend is connected to API properly.
Will serve as a basis for the hot-loadable component.
=> add NewRemediationButton

src/components/ResolutionModal/ChooseResolutionModal.scss
It looks like PF updated and messed up some radio buttons and the labels.
Before:
After:
=> fixing checkboxes on choose resolution modal

src/Utilities/urls.js
This PR https://github.com/RedHatInsights/insights-inventory-frontend/pull/49 removes the need of `/entity/` in path to inv detail.
=> Inventory path changed and entity was removed

src/Utilities/urls.js
https://projects.engineering.redhat.com/browse/RHCLOUD-2673
The actual url should be something like
`https://cloud.redhat.com/insights/rules/foo` instead of `https://cloud.redhat.com/insights/overview/by_id/foo`
=> change insights segment from /overview to /rules

package-lock.json, package.json, src/actions.js, src/components/ExecuteButton.js, src/constants.js, src/containers/ExecuteButtons.js, src/store/reducers.js
Bind endpoint to Execute Playbook button.
To show `Reset etag` button you should type `localStorage.setItem('remediations:fifi:debug', true)` into browser console.
=> Bind endpoint to Execute Playbook button

src/components/ActivityDetails.js, src/components/ExecutorDetails.js, src/store/reducers.js
Fixes issues:
- the filters/buttons are not on the same row as pagination
- no padding between the filter and the button
- when a system row of a finished system is expanded it starts to poll (even though the system is not running)
- when I expand a row it's order in the list changes
=> Fix sorting change when expanding item

src/components/ActivityDetails.js, src/components/Alerts/NoReceptorBanner.js, src/components/Alerts/UpsellBanner.js, src/components/Alerts/__tests__/__snapshots__/UpsellBanner.test.js.snap, src/components/ConfirmationDialog.js, src/components/DeleteButton.js, src/components/ExecuteButton.js, src/components/ExecutorDetails.js, src/components/ExecutorDetails.scss, src/components/Layouts/DescriptionList.scss, src/components/RemediationActivityTable.js, src/components/RemediationActivityTable.scss, src/components/RemediationDetailsSystemDropdown.js, src/components/RemediationDetailsTable.js, src/components/RemediationTable.js, src/components/Status.scss, src/components/SystemDetails.js, src/components/SystemDetails.scss, src/components/SystemForActionButton.js, src/components/statusHelper.js, src/routes/RemediationDetails.js, src/skeletons/ActivityDetailsSkeleton.js, src/skeletons/ExecutorDetailsSkeleton.js, src/skeletons/RemediationDetailsSkeleton.js
Overall
- Playbook summary sentence case - Should be “Playbook summary” 
- Buttons should be sentence case (“Execute playbook”, “Download playbook”)
Actions
- Labels look like they are 16px, should be 14px heading label 
- Auto reboot to be 2 words
- “Issues” tab should be “Actions” to match what is shown. 
- "Remove System" Should be not red text as per UXD guidelines
- System modal align buttons to the left
- Issues table Remove action should be in a secondary button style
- activity table Spacing in the expand pane is off. 
- status tooltip says “systems” after all the numbers
- fixed floating tooltip - should be closer to the actual content. Hopefully centered on it.
- Status text should have min-width for the label so we can line up all these things (85px)
- adds a banner when …
=> Low hanging fruit papercuts (phase 1)

src/components/ExecuteButton.js, src/components/ExecutorDetails.js, src/components/RemediationTable.js, src/components/Status.scss, src/components/SystemDetails.js, src/components/SystemDetails.scss, src/routes/RemediationDetails.js
Various visual/styling changes:
- Execute modal status
- Truncate Satellite names, add tooltip
- Use secondary style without icon for all Download playbook buttons
- Code view dost not break table when row is too long
- Code view line numbers match the row
- Use same status in remediation detail as used at other palces
=> Visual changes

src/components/ExecutorDetails.js, src/components/SystemForActionButton.js
We are working on inventory refactoring, since we'd like to fully use hooks and such we have to use App's react dependency. With this being used react-redux needs to be passed from application as well. If you are cautious about the size of your bundle I can pick only the functions really required by inventory.
=> Pass react redux to inventory loader as well

src/components/Modals/ExecuteModal.js, src/components/Modals/ExecuteModal.scss, src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap, src/components/RemediationTable.js
Was missing two props when calling ExecuteModal from RemediationTable. Also added a check to make sure that the getEndpoint action completed before attempting to read 'sources.data' from redux. When running an execute from the landing page the ExecuteModal would attempt to read sources.data[id] before sources contained any data.
@PanSpagetka Let me know if you have a problem with this approach since you're more familiar with that workflow.
=> Adding sources and getEndpoint props to ExecuteModal call

src/components/ExecutorDetails.js, src/components/SystemForActionButton.js
There is a new feature brewing in chrome, building chrome with webpack [1]. This PR passes newly required dependencies. In future we'll use Federated modules [2] so there won't be a need for these changes, but this is required as a mid-step solution.
[1] https://github.com/RedHatInsights/insights-chrome/pull/842
[2] https://webpack.js.org/concepts/module-federation/
=> Pass pf-react-core to inventory

src/components/EmptyStates/EmptyActions.js, src/components/RemediationSummary.js
This change allows the frontend (specifically within the chart on the details view) to calculate the number of resolved issues from a filtered list of issues. This is primarily to ensure that the number of resolved issues does not exceed the number of issues shown in the table below the chart (this could occur if you have an issue that has been resolved, but is no longer found in advisor/vulnerability/etc). Further work/design will be needed for these edge cases.
=> Get resolved issue count from filtered issues

src/components/ExecuteButton.js, src/components/__tests__/__snapshots__/ExecuteButton.test.js.snap, src/routes/RemediationDetails.js
https://issues.redhat.com/browse/RHCLOUD-10306
Added disabled state tooltip texts depending on the context:
- 'Your account must be configured with Cloud Connector to execute playbooks.'
- 'You do not have the required execute permissions to perform this action.'
- 'Your account must be entitled to Smart Management to execute playbooks.'
"Execute playbook" button is always rendered from now, also when not entitled to Smart Management.
Updated snapshots.
=> Add tooltip to disabled "Execute playbook" button

src/components/ConfirmationDialog.js, src/components/Modals/SystemsStatusModal.js
Use the Modal variant rather than a percentage so that the modal renders properly in mobile.
jira: https://issues.redhat.com/browse/RHCLOUD-13022
Before
After
=> Fix broken modal styling in mobile

src/components/Modals/ExecuteModal.js, src/components/Modals/__tests__/__snapshots__/ExecuteModal.test.js.snap
Direct connection was always saying "checking", looks like the status was being set to "loading". Unsure why we were doing that, but removing it seems to fix the issue.
If there's a better way to do this because that line was needed, someone please let me know 😄 
@PanSpagetka 
This also adds the right classname to the modal so that the styles are there
=> fix preflight modal check

src/Utilities/utils.js, src/modules/RemediationsModal/common/SystemsTable.js, src/modules/RemediationsModal/steps/reviewSystems.js, src/modules/tests/utils.test.js
Fixes: https://issues.redhat.com/browse/RHCLOUD-14888
- implemented local sorting by `name` for Remediation wizard InventoryTables
- hidden not possible working options
- added test coverage for the sorting helper function
- removed a bug causing wrong systems counts because of duplicates
- updated tests
@karelhala
=> Fix sorting in the Remediation wizard Inventory tables

src/modules/RemediationsButton.js
When the remediation was created it didn't properly send `onRemediationCreated` because it was in wrong place.
=> Move onRemediationsCreated to data structure

src/Utilities/utils.js, src/modules/RemediationsModal/steps/progress.js, src/modules/tests/steps/progress.test.js
jira: https://issues.redhat.com/browse/RHCLOUD-15802
- use template string to construing the URL
- use link for the review step link (better accessibility)
The `remediationUrl` method was returning an invalid URL
1. it had multiple `/beta` segments
2. it was concatenated with `,` character instead of `/`. I don't know why yet. I've used the exact same code in codesandbox and also in the browser console and the result was correct. But when used in code, we got the mangled URL. We can spend more time debugging it, but since the issue is reproducible in prod we need a fix ASAP.
=> Fix final step link

src/Utilities/utils.js, src/modules/RemediationsButton.js
Remediations here were matching permissions literally and not substituting *, which means for example when user has `remediations:*:*` permission it won't let them do the Remediate action requiring `remediations:remediation:write`, even though it should, solution is to match any substring between : to *, instead of doing whole string matching with ===
This lead to Remediation button not working when it should in Vulnerability app.
=> Substitute * in RBAC permission for Remediate button

src/modules/RemediationsButton.js, src/modules/RemediationsModal/NoDataModal.js
Ticket: https://issues.redhat.com/browse/VULN-2041
Mockup: https://marvelapp.com/prototype/gbhbja0/screen/83265660
1. User has no items selected -> Remediate button should be disabled - this is controlled by apps
2. User has selected items, but none are remediable (remediation is manual or there is none) -> Remediation button
3. User has selected items and some or all are remediable -> show Wizard and remediate normally
This PR implements situation 2.
Apps using Remediation button component are responsible for disabling/enabling the button. Apps should send `false` instead of data object, when nothing selected is remediable.
=> Display no data modal when no remediable issues are passed

src/components/DeleteButton.js, src/containers/DeleteButtons.js
Previously the Confirmation dialog was showing wrong text when user clicked Remove Action
Fix:
=> Fixed Dialog text in Remove Action

src/containers/DeleteButtons.js
[ESSNTL-2666](https://issues.redhat.com/browse/ESSNTL-2666)
When deleting multiple actions the dialog has "actions" in plural
Before:
After:
=> fix: ESSNTL-2666 - added pluralization when deleting multiple actions

src/components/RemediationDetailsDropdown.js
[ESSNTL-2670](https://issues.redhat.com/browse/ESSNTL-2670)
Previously when you cancelled a deletion of a playbook you would get a notification of deletion.
Fixed dialog text
Before:
After:
=> fix: ESSNTL-2670 - fix playbook delete button

src/components/ExecuteButton.js, src/components/Modals/ExecuteModal.js, src/components/RemediationTable.js, src/components/__tests__/ExecuteButton.test.js, src/components/__tests__/__snapshots__/ExecuteButton.test.js.snap, src/components/statusHelper.js
This PR [resolves](https://issues.redhat.com/browse/ESSNTL-1482) the connection status column on ExecuteModal.
It needs to be checked against side effects as I do not have full understanding of connection status use-cases. BUT, I have indentified that RHC hosts do not have availability info and this is breaking `combineStatuses` function result. Thus, I have introduced a single condition to prevent availability checking for RHC hosts only.
These hosts can be used to reproduce the issue, one of them is satellite and another is RHC:
1. ci-vm-10-0-147-6.hosted.upshift.rdu2.redhat.com 
2. ci-vm-10-0-152-181.hosted.upshift.rdu2.redhat.com
Also thre are three remediations for those hosts. To view them, log in to console.redhat.com as the insights-qa user, and search for the following …
=> fix ExecutModal connection status

.eslintrc.yml, src/hooks/table.js, src/hooks/table.test.js, src/routes/Home.js
This fixes: https://issues.redhat.com/browse/REMEDY-56.
Users should be able to:
1. Select page
2. Deselect all selected remediations
in remediations table. Selecting all existing remediations will be done later, when there is an API to fetch all IDs of those remediations.
=> fix(REMEDY-56): enable to deselect selected remediations

build_deploy.sh, package.json, pr_check.sh
This PR adds the `build_deploy.sh` and `pr_check.sh` scripts for the new front end deployment system. Additionally, this disables cache for jest as it breaks the frontend system.
=> [RHCLOUD-20271] - Add build scripts for new front end deployment

src/Utilities/utils.js
resolves https://issues.redhat.com/browse/REMEDY-83
Actually, redirect to stable happened only after second remediation. I suspect that `href` to playbook caused `document.baseURI` to change from `https://stage.foo.redhat.com:1337/beta/` to `https://stage.foo.redhat.com:1337/`. Therefore we have to check and remove `beta/` from `document.baseURI`
=> fix(Progress): REMEDY-83 - Fix beta wizard links

src/AppEntry.js
To reproduce:
- Navigate to `/insights`
- Click on Remediations in the side nav (may have to do this multiple times)
This issue is intermittent. If the page loads properly, then you'll need to navigate back to `/insights` and reload the page and start the process all over again. Eventually, you'll get the errors.
You will also see this issue of you navigate to `/insights` and then click the "All apps and services" button in the header and choose "Remediations" from the "Ansible Automation Platform" section.
This PR fixes that issue.
=> [REMEDY-219] Fix remediations loading errors

package-lock.json, package.json
Run `npm audit fix` to fix 12 vulnerabilities (1 moderate, 9 high, 2 critical).
Pin `follow-redirects` to version 1.14.9 to fix a CVE: https://issues.redhat.com/browse/ESSNTL-2139
=> chore: Resolve CVEs

src/App.js, src/AppEntry.js
To reproduce the bug:
- Navigate to /insights
- Click Toolkit -> Remediations in the side nave
- After the page loads, click Remediations in the side nave again
It is an intermittent error, and sometimes I have to try it 6 or 7 times to get it to error, but it does eventually do it. This should be fixed.
=> [REMEDY-219] Fix new loading issue

config/dev.webpack.config.js, src/components/ExecutorDetails/Columns.js, src/components/ExecutorDetails/ExecutorDetails.js, src/components/SystemsTable/Columns.js, src/components/SystemsTable/SystemsTable.js, src/components/SystemsTable/helpers.js
This resolves the regression on the Executor details page. The regression was caused while resolving REMEDY-277. It appears that Executor details page also uses the mergedColumns function with the obsolete column merging logic. This PR updates the usage of the mergedColumn function to be compatible for both pages. The regression is only on stage env.
1. Run the PR against prod env. The dev-webpack.config is prepared for running the PR agains PROD, once approved I will remove this.
2. search for playbook 'mkholjur-test-search'
3. click on the activities tab
4. open one activity detail
5. Observe that the inventory module does not fail to load.
=> fix(InventoryColumns): use one custom columns array to merge with inventory default columns

config/dev.webpack.config.js, src/components/RemediationDetailsTable.js, src/components/SystemsTable/SystemsTable.js
Fixing bulk select in Actions and Systems tab
https://issues.redhat.com/browse/REMEDY-283
https://issues.redhat.com/browse/REMEDY-145
https://issues.redhat.com/browse/REMEDY-90
I added 2 buttons:
**Select page (number of rows)
Select all (number of values in the entire table)**
I improved the behavior of the select page buttons
**Behavior**: User has a list of things, 10 per page, 5 pages (50 items total):
First page - “Select page” --> 10 items selected
Nav to second page - “Select page” --> 20 items selected (adds to the selection)
Nav to third page - "Select page" --> 30 items selected (adds to the selection)
To unselect the third page -> "Select page" --> 20 items selected …
=> fix(detailsTable): bulk select fix

src/modules/RemediationsModal/common/SystemsTable.js
Associated Jira ticket: # https://issues.redhat.com/browse/ADVISOR-3053
After Inventory onRefresh caches the options passed and prevents successive function triggers
with the same options, we need to remove this obsolete prop.
Run the remediation app with any app that you are comfortable with and open the remediation modal. When you go to the 'Review systems' step, observe that the table loads as expected.
=> fix(ADVISOR-3053): remove obsole onRefresh prop

src/components/PlaybookCard.js
Steps to Reproduce:
1. Go to remediations
2. Click the three dots on a specific playbook card
3. Click "Download playbook" and you get the download zipped although it's a single playbook
If you check the checkbox of a single playbook then click the large Download button above. You get it unzipped. This is the anticipated action when downloading a single playbook. This PR fixes this interaction.
See the card comments for additional information.
=> fix(REMEDY-122): Broken "Download playbook" on remedation card

src/api/index.js
[RHCLOUD-24866](https://issues.redhat.com/browse/RHCLOUD-24866)
downloading playbook from remediations should not open a new window anymore
=> RHCLOUD-24866

src/components/RemediationDetailsDropdown.js
Associated Jira ticket: [RHINENG-5917](https://issues.redhat.com/browse/RHINENG-5917)
Returned playbook renaming behavior as it was designed initially
1. Create a playbook with some name
2. Try to rename it and use empty value
3. Playbook should be named "Unnamed Playbook"
Before the change you had playbook without name at all that looked ugly
[Screencast from 2024-01-15 15-46-27.webm](https://github.com/RedHatInsights/insights-remediations-frontend/assets/33912805/b3ce905c-36e9-4d23-8ff2-71d7f69c81ba)
=> fix(RHINENG-5917): Use default name instead of empty playbook name

src/components/RemediationActivityTable.js
It seems that occasionally and for reasons unknown, the last_name is not recorded with the remediation, so this PR has the frontend display the username if the last_name is missing, otherwise it displays the first_name and last_name as usual.  Perhaps not the best solution (finding out why the last_name isn't being recorded is the best solution), but displaying 'my-user-name' in the UI is slightly better than displaying 'Firstname undefined'.
https://issues.redhat.com/browse/RHINENG-4944
Before the change, last_name is displayed as 'undefined':
After the change, the user's username is displayed instead:
=> fix(RHINENG-4944): Display the username if last_name is missing

src/Utilities/useConnectionStatus.js, src/routes/RemediationDetails.js, src/routes/RemediationDetails.test.js
Associated Jira ticket: # ([issue](https://issues.redhat.com/browse/RHINENG-3750))
This adds a new endpoint and checks the connection status of the remediation. if the connection status is anything but 'connected', it should be disabled
- Open the network tab : Bring down the PR and select a remediation
- in the network tab, filter the results with connection_status
- Open the data and look through the data object for a connection_status key/value pair. If the value is connected (and other conditionals are met) the execute button should be enabled,
- Select multiple remediations, if any of them have a status other than 'connected' and the button is available, then this PR needs more work.
- You could remediate when the connection_status was not 'connected'
- You can only execute with this …
=> fix(RHINENG-3750): Communicate in UI when remediations is disabled

src/components/Modals/SystemsStatusModal.js
Associated Jira ticket: [RHINENG-4956](https://issues.redhat.com/browse/RHINENG-4956)
Move action below title in Systems for action modal. If the action string were too long it would overflow the modal title.
Very long action string should no longer overflow the modal.
=> fix: RHINENG-4956 Move action below title in Systems for action modal

src/modules/RemediationsButton.js, src/modules/RemediationsModal/NoDataModal.js
Change wording in NoDataModal when a system with no advisories is remediated
Associated Jira ticket: RHINENG-3123
1. Run this PR with https://github.com/RedHatInsights/patchman-ui/pull/1174
2. Go to Patch systems page
3. Select system with no advisories available
4. The modal should have changed wording
=> change(NoDataModal):RHINENG-3123 change text for no advisory systems

src/components/RemediationDetailsTable.js
This PR addresses issue [#RHINENG-4946](https://issues.redhat.com/browse/RHINENG-4946)
With this PR's changes, we should be able to see that when deleting an Action, the Bulk Selector's number of selected items is being updated
1. Navigate to a remediation that has several Actions
2. Select one or more Actions
3. Click the 'Remove Action' button at the top of the table
4. The Bulk Selector still counts it as selected, although it is no longer present
=> fix(RHINENG-4946): RemediationDetailsTable - Bulk Selector is not updated when an Action is deleted

src/modules/RemediationsModal/steps/review.js, src/modules/tests/steps/review.test.js
Associated Jira ticket: [RHINENG-4974](https://issues.redhat.com/browse/RHINENG-4974)
Description of changes: Changes the 'Turn on/off autoreboot' from a hyperlink to a switch.
Screenshot before the change:
Screenshot after the change:
=> feat(RHINENG-4974): Change autoreboot link to a switch

src/Utilities/useConnectionStatus.js, src/components/ExecuteButton.js, src/routes/RemediationDetails.js, src/routes/RemediationDetails.test.js
Adds a popover to explain why your remediation cant be executed if its disabled.
Associated Jira ticket: # ([issue](https://issues.redhat.com/browse/RHINENG-7065))
Select a Remediation to go to details
hover over the disabled executable button (needs to be disabled to see popover)
Popover should match mocks:  https://www.figma.com/proto/4SzBpdiqHzLDtItBG3aisz/Remediations?page-id=0%3A1&type=design&node-id=243-6441&viewport=358%2C-1266%2C0.16&t=qCljog3Q1nHLY3d1-1&scaling=min-zoom&starting-point-node-id=133%3A8687
Popover says 'Unable to execute'
With the addition of the 403 error, the structure of the data coming back on a 403 is (removed unrelated key/value pairs )
{
"errors": [
{
"status": 403,
}
]
}
=> feat(RHINENG-7065): Add popover to explain disabled statuses

config/setupTests.js, src/components/ExecutorDetails/ExecutorDetails.js, src/components/PlaybookCard.js, src/components/RemediationTable.js, src/components/__fixtures__/remediations.fixtures.js, src/components/__tests__/PlaybookCard.test.js
Associated Jira ticket: # RHINENG-4953
When a selected playbook is archived, and archived playbooks are not visible, that selection remains in the bulk select.
- Navigate to Remediations
- Ensure only non-archived playbooks are being shown via toolbar action kebab
- Select checkbox of a playbook
- Archive playbook from card action kebab
The playbook remains selected (see Bulk Selector).
With this PR, when only non-archived playbooks are being shown, and we archive a selected playbook, that selection should not remain.
On the other hand, if we are viewing all playbooks (archived and non-archived) and we archive a selected playbook, the selection should remain.
=> fix(RHINENG-4945): Fix bulk select on archive

src/Utilities/useConnectionStatus.js, src/Utilities/utils.js, src/components/ExecuteButton.js, src/components/RemediationDetailsTable.js, src/components/__tests__/ExecuteButton.test.js, src/routes/RemediationDetails.js
Updates the conditionals in the popover in remediation details page. 
Associated Jira ticket: # ([issue](https://issues.redhat.com/browse/RHINENG-7065))
Fixes three issues:
The tooltip incorrectly always states that there are 4 systems in a remediation plan (now updated)
-Spacing is incorrect (updated, added pf class)
-When RHC Manager (config-manager) is disabled, the execute button never loads at all (updated, i had placed setAreDetailsLoading(false) only in the try statement)
Open up a remediation detail, verify the the system count matches up and that the spacing looks fine.
If youre unaware of how to disable to rhc config, you can just comment out 'detailsError' prop and define it as a 403. 
Before: 
After:
=> fix(RHINENG-7065): Fix popover conditions

src/Utilities/utils.js, src/modules/RemediationsModal/steps/reviewSystems.js
In this example, localhost is a bootc system.  You can see there is an error and the next button is greyed out. Advisor systems are an exception to this rule. They can remediate.
=> feat(RHINENG-9195): Block bootc systems

src/Utilities/useConnectionStatus.js, src/components/ExecuteButton.js, src/routes/RemediationDetails.js, src/routes/RemediationDetails.test.js
Associated Jira ticket: # ([issue](https://issues.redhat.com/browse/RHINENG-7065))
The popover in remediations details should be enable regardless if the button is disabled or not.
'Connected systems' should only come from the connection_status endpoint where the object actually says 'connected'. if there are not connected systems, the execute button should be disabled. The total amount of systems should also come from this endpoint.
=> fix(RHINENG-7065): Refactor popover to include enabled execute button + new api

src/Utilities/useRemediationsList.js, src/Utilities/useVerifyName.js, src/components/Dialogs/TextInputDialog.js, src/components/RemediationDetailsDropdown.js, src/routes/RemediationDetails.js
Associated Jira ticket: # [(issue)](https://issues.redhat.com/browse/RHINENG-8656)
This removes the ability to name a remediation against one that already exist. No duplicates being possible moving forward. (Seperate PR for creation of remediation will be made)
grab any remediation name, copy it, and then go to the details of any other remediation.
Then try to rename the remediation with the copied string. The button should be disabled.
I added a timeout that is reset when the user types, so the logic shouldnt perform until the user is done typing (unless they type reaaaaallllly slowly).
While the logic is happening, a spinner takes the buttons place to indicate to the user that something is happening in the background as opposed to it just being disabled.
You could duplicate a …
=> feat(RHINENG:8656): Playbook rename modal doesnt allow duplicate names

src/modules/RemediationsModal/schema.js
Associated Jira ticket: # ([issue](https://issues.redhat.com/browse/RHINENG-9877))
In the remediation modal, when creating a playbook, selecting an existing playbook resulted in not being able to move forward. This updates the validation so that you can click an existing playbook, and so error messaging still works on the text field
You can check via anywhere the button is available but for ex.
Advisor - recommendations -> rec details -> System details and remediate button.
- Select an existing remediation and see that you can proceed to the next step.
- Select create a playbook and verify that you still cant move forward when you have a duplicate name.
=> fix(RHINENG-9877): Update Validation for Remediations modal

src/modules/RemediationsModal/common/ExistingPlaybookTypeahead.js, src/modules/RemediationsModal/steps/selectPlaybook.js, src/modules/tests/steps/selectPlaybook.test.js
Associated Jira ticket: # 8088
When you are creating playbook and choose from Existing playbooks (Add to existing playbook) select appears without search option. Seems it happened after Patternfly 5 migration. 
To repro:
- Choose and click a system in inventory
- From the system details page, click the Vulnerability tab Pick CVE(s) and click on Remediate button
- When modal opens - click in the "Select playbook" box
This box should allow typeahead, which filters the existing playbooks as you type. But this feature seems to have been removed from the PF component we were using and have been moved to the Select component.
This PR refactors this box to allow typeahead.
=> fix(RHINENG-8088): refactor select playbook typeahead

src/components/SystemsTable/ConnectionStatusCol.js, src/components/SystemsTable/helpers.js
FIxes the system table bug where if RBAC is disabled then the table breaks.
To test log in , navigate to Inventory> System Configuration> RHC 
Edit
Disable the first option
Then go to remediations with systems in it and observe that the table loads, since the network request should all return 403, the status on the column will always be unknown
=> fix(RHINENG-9382): Connection Status column error condition

config/setupTests.js, src/components/ExecuteButton.js, src/components/__tests__/ExecuteButton.test.js, src/components/statusHelper.js
https://issues.redhat.com/browse/RHINENG-11983
How to test:
1. Go to detail of any playbook which can be executed
2. Hover over the "Execute playbook" button
3. The two links in the shown tooltip should take you to the corresponding app without having to reload the whole page
4. Click on the "Execute playbook" button
5. The "RHC (Red Hat connector)" link should take you to the corresponding app without having to reload the whole page
=> Update <a> to <Link> when Executing playbook

src/routes/Home.js
https://issues.redhat.com/browse/RHINENG-4954
Before -- after deleting the playbook the filter did not reset, but the cards below were fetched as if the filter wasn't applied
After -- after deleting the playbook the filter is reset and cards are shown correctly
=> Reset  filter after Playbook deletion

config/setupTests.js, package.json, src/actions.js, src/components/ExecutorDetails/ExecutorDetails.js, src/components/__fixtures__/remediations.fixtures.js, src/components/__tests__/ExecutorDetails.test.js, src/constants.js, src/store/reducers.js
Playbook log doesn't display properly after inital load.
To repro:
- Automation Toolkit > Remediations > A playbook  > Activity > The data that the playbook ran successfully > Direct connected
- At this point the playbook log will flash on screen and disappear
- Click on the hostname
The issue was that playbookRunSystemDetails is a redux variable that remains after initial load. So when the playbook log is loaded again, the log viewer somehow only captures part of the string or none at all.
The best way to handle this issue is to clear the variable in redux on inital load to ensure there are no incorrect states.
=> fix(RHINENG-11503): Playbook log doesn't display properly

src/components/ExecutorDetails/ExecutorDetails.js
If you run a remediation, ( I recommend hitting jaudet-test:pause5m for testing), and try to view its output while running, it would fail and the user could never open up the output. 
With this fix it allows you to open the table and view the output. 
To test: 
Automation Toolkit > Remediations > A playbook ( jaudet-test:pause5m) > Execute it > Activity > Click the latest one > click 'Direct connected' > observe the Run Status is running in the page header, and then expand one of the systems. (or both).
With this one specifically you may notice for the first few seconds there is no output, but thats because its still booting up and there is legitimately no output.
=> fix(RHINENG-14395): Playbook output is visible while executing

src/routes/RemediationDetails.js
https://issues.redhat.com/browse/RHINENG-9779
Alters layout of remediation details page header so that if theres a really long name it doesnt move the buttons, but instead just wraps under itself:
Before PR: 
With PR
=> fix(RHINENG-9779): Change Details Page Header layout

src/components/RemediationSummary.js, src/components/Status.scss, src/components/statusHelper.js
This PR adds color back to the status summary. To test, navigate to a remediations details and check the status summary.
Before: 
After: 
What its supposed to look like according to ticket:
=> fix(RHINENG-13431): Re-add color to Status Summary

src/modules/RemediationsModal/steps/review.js, src/modules/tests/steps/review.test.js
https://issues.redhat.com/browse/RHINENG-14725 
This simply renames the toggle in remediations step 3.
Navigate to anywhere you can remediate, in this case Advisor
Advisor -> a recommendation you can remdiation (a non-manual one)
select a system -> click remediate process, get to step 3
Desired behavior:
Toggle is gray: "The playbook ___ does not auto reboot systems." and "Auto reboot is off"
Toggle is blue: "The playbook ___ auto reboots systems." and "Auto reboot is on"
With this PR:
=> fix(RHINENG-14725): Reword auto reboot toggle

src/Utilities/utils.js
Fixes https://issues.redhat.com/browse/RHINENG-10618
- Remove unnecessary object construction with instant deconstruction
- Do not overwrite `total` property of the spread `data` object -- it contains the correct system count since `total` property includes row count which is double due to including expand cells as rows
=> fix(Remediation wizard): Fix incorrect system count in the pagination

src/modules/RemediationsModal/steps/review.js
To test, go to any app where the Remediation modal lives and go through the steps until you get to the Remediation review step. There is an "Auto reboot is on/off" switch. Inspecting it should reveal the new ouiaID.
One place to check is Vulnerability. Simply select a CVE and go to the CVE details table. From the details table, add systems and then click the "Remediate" button to open the Remediate modal.
=> fix(RHINENG-15230): Add ouidID to autoreboot switch

src/components/RemediationDetailsDropdown.js, src/components/SystemsTable/ConnectionStatusCol.js, src/components/SystemsTable/IssuesColumn.js, src/routes/RemediationDetailsComponents/ActionsContent/ActionsContent.js, src/routes/RemediationDetailsComponents/DetailsPageHeader.js, src/routes/RemediationDetailsComponents/ExecutionHistoryContent/ExecutionHistoryContent.js, src/routes/RemediationDetailsComponents/ExecutionHistoryContent/LogCards.js, src/routes/RemediationDetailsComponents/SystemsContent/ActionsModal/ActionsModal.js, src/routes/RemediationDetailsComponents/SystemsContent/Cells.js
This updates the content for Actions And Systems page
it can be a little confusing to look at all the wording changes, but here are 2 documents going over all the wording/icon changes
https://docs.google.com/document/d/1agqdtbbeb3ZwvLMGV_B4IlHpaWG6CAzQjGW1pxb2DEA/edit?tab=t.0
https://docs.google.com/document/d/1V3rmE8MoE2cmvVJ8OrfPQL3uGeRGHmoYhg4dLGh2dSs/edit?tab=t.0
The changes on systems pages: 
- Details page systems tab -> select an item in actions column:
- Title for modal is now 'Planned remediation actions.'
- Details Page actions tab
- When renaming a remediation (top right elipse) the title of the modal is name 'Rename remediation plan?'
- The warning text (for when you try to rename a remediation to an existing one) is now `Enter a unique name that does not already exist in your …
=> Actions and systems

src/App.js, src/App.test.js, src/Routes.js, src/components/NoRemediationsPage.js, src/routes/RemediationDetails.js, src/routes/RemediationDetails.test.js, src/routes/RemediationDetailsComponents/PlanNotFound.js, src/routes/RemediationDetailsComponents/PlanNotFound.test.js
This adds a 404 page for when an remediation ID results in a 404 on the details page (bookmarked a deleted plan)
Adds a no permissions page 
fixes the styling in PF6 No remediations page as well as updates the endpoint used to determine if the user has remediations or not. 
For testing reroute: you can use insights-qa 
Navigate to the details page of any remediation and then alter the id in the url to mimic a deleted plan, and see you are rerouted to the home page 
For testing **NoRemediations**: policies-noaccess-user-1 - with this user you can test a user with no remediations WITH permissions that can see the updated NoRemediationsPLans page styling (Note: This page is scoped by the orgs remediations, no if a user has remediations).
For the no access, if you cant alter/create a user, …
=> feat(RHINENG-19641): Add rerouting and No permissions page
